name: ci

on:
  push:

env:
  TEST_TAG: us-central1-docker.pkg.dev/ervin-cloud-run-demo2/docker-demo/hello:test
  LATEST_TAG: us-central1-docker.pkg.dev/ervin-cloud-run-demo2/docker-demo/hello:latest

concurrency:
  group: main
  cancel-in-progress: true  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      imageid: ${{ steps.docker_push.outputs.imageid }}
      digest: ${{ steps.docker_push.outputs.digest }}
    steps:
      - uses: 'actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac'
      - run: |
          # reset timestamps:
          find . -type f -exec touch --date="@0" {} +  
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "projects/638457069405/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: 'github@ervin-cloud-run-demo2.iam.gserviceaccount.com'
          token_format: access_token
          access_token_lifetime: '600s'
      - uses: 'docker/login-action@v2'
        with: 
          registry: us-central1-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    
      - name: Build and export to Docker
        id: docker_push
        uses: docker/build-push-action@v5
        #env:
        #  SOURCE_DATE_EPOCH: 0
        with:
          context: .
          # load: true
          push: true
          file: placeholder.dockerfile
          tags: ${{ env.TEST_TAG }}
          cache-to: 'type=gha,mode=max'
          cache-from: 'type=gha'
          build-args: |
            SOURCE_DATE_EPOCH=0
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.TEST_TAG }}
          format: 'spdx-json'
          output: '/github/workspace/results.spdx'
          exit-code: '0'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - run: |
          # upload sbom
          gcloud artifacts sbom load \
            --source results.spdx \
            --uri ${{ env.TEST_TAG }}  
  provenance:
    needs: [build]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    # if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.9.0
    with:
      image: us-central1-docker.pkg.dev/ervin-cloud-run-demo2/docker-demo/hello
      digest: ${{ needs.build.outputs.digest }}
      gcp-workload-identity-provider: "projects/638457069405/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
      gcp-service-account: 'github@ervin-cloud-run-demo2.iam.gserviceaccount.com'
      private-repository: true
      # continue-on-error: true